name: mobile_parent
version: 0.0.0
publish_to: "none"
description: Flutter app for parents. Placeholder.
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.0
  flutter_riverpod: ^2.5.1
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  jwt_decode: ^0.3.1
  share_plus: ^10.0.0
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_common:
    path: ../../libs/flutter-common
  flutter_notifications:
    path: ../../libs/flutter-notifications

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  freezed: ^2.5.8
  json_serializable: ^6.9.5
