name: mobile_parent
version: 0.0.0
publish_to: "none"
description: Flutter app for parents. Placeholder.
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.0
  flutter_riverpod: ^2.5.1
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  jwt_decode: ^0.3.1
  share_plus: ^10.0.0
  flutter_common:
    path: ../../libs/flutter-common

dev_dependencies:
  flutter_test:
    sdk: flutter
