name: mobile_teacher
version: 0.0.0
publish_to: "none"
description: Flutter app for teachers and therapists.
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.2.0
  dio: ^5.7.0
  url_launcher: ^6.2.5
  intl: ^0.19.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_common:
    path: ../../libs/flutter-common
  flutter_notifications:
    path: ../../libs/flutter-notifications

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4
  golden_toolkit: ^0.15.0
  network_image_mock: ^2.1.1
  patrol: ^3.6.1
  clock: ^1.1.1
  fake_async: ^1.3.1
