name: mobile_learner
version: 0.0.0
publish_to: "none"
description: Flutter app for learners. Placeholder.
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.0
  flutter_riverpod: ^2.5.1
  provider: ^6.1.2
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  jwt_decode: ^0.3.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  audioplayers: ^6.0.0
  flutter_tts: ^4.0.2
  flutter_svg: ^2.0.10+1
  speech_to_text: ^7.0.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  sqflite: ^2.3.3+2
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  flutter_common:
    path: ../../libs/flutter-common
  flutter_notifications:
    path: ../../libs/flutter-notifications

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
