name: mobile_learner
version: 0.0.0
publish_to: "none"
description: Flutter app for learners. Placeholder.
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.0
  flutter_riverpod: ^2.5.1
  flutter_common:
    path: ../../libs/flutter-common

dev_dependencies:
  flutter_test:
    sdk: flutter
